# Generated by Django 4.2.14 on 2026-06-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="โทรศัพท์")),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="รหัสไปรษณีย์"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="เมือง")),
                ("province", models.CharField(blank=True, max_length=100, verbose_name="จังหวัด")),
                (
                    "country",
                    models.CharField(default="Thailand", max_length=100, verbose_name="ประเทศ"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="รูปโปรไฟล์"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "โปรไฟล์ผู้ใช้",
                "verbose_name_plural": "โปรไฟล์ผู้ใช้",
            },
        ),
    ]
