# Generated by Django 4.2.14 on 2026-06-16 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "receipt_number",
                    models.CharField(max_length=100, unique=True, verbose_name="เลขที่ใบรับ"),
                ),
                ("receipt_date", models.DateTimeField(auto_now_add=True, verbose_name="วันที่รับ")),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
            ],
            options={
                "verbose_name": "ใบเสร็จการรับสินค้า",
                "verbose_name_plural": "ใบเสร็จการรับสินค้า",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="จำนวน",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="จำนวนสำรอง",
                    ),
                ),
                ("received_date", models.DateTimeField(verbose_name="วันที่รับสินค้า")),
            ],
            options={
                "verbose_name": "สต็อก",
                "verbose_name_plural": "สต็อก",
                "ordering": ["product"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="ชื่อคลัง")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="รหัสคลัง")),
                ("address", models.TextField(verbose_name="ที่อยู่")),
                ("phone", models.CharField(max_length=20, verbose_name="เบอร์โทรศัพท์")),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้จัดการ",
                    ),
                ),
            ],
            options={
                "verbose_name": "คลังสินค้า",
                "verbose_name_plural": "คลังสินค้า",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("zone", models.CharField(max_length=50, verbose_name="โซน")),
                ("shelf", models.CharField(max_length=50, verbose_name="ชั้น")),
                ("bin", models.CharField(max_length=50, verbose_name="ตู้")),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="warehouse.warehouse",
                        verbose_name="คลัง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตำแหน่งเก็บสินค้า",
                "verbose_name_plural": "ตำแหน่งเก็บสินค้า",
                "ordering": ["zone", "shelf", "bin"],
                "unique_together": {("warehouse", "zone", "shelf", "bin")},
            },
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("in", "รับเข้า"),
                            ("out", "ออก"),
                            ("adjustment", "ปรับปรุง"),
                            ("damage", "เสียหาย"),
                            ("return", "คืน"),
                        ],
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                ("quantity_change", models.IntegerField(verbose_name="เปลี่ยนแปลงจำนวน")),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="เลขที่อ้างอิง"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำ",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="warehouse.stock",
                        verbose_name="สต็อก",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติสต็อก",
                "verbose_name_plural": "ประวัติสต็อก",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stock",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.stocklocation",
                verbose_name="ตำแหน่ง",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="ecommerce.product",
                verbose_name="สินค้า",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="warehouse.warehouse",
                verbose_name="คลัง",
            ),
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "ผ่าน"),
                            ("rejected", "ปฏิเสธ"),
                            ("conditional", "ตามเงื่อนไข"),
                        ],
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("quantity_checked", models.IntegerField(verbose_name="จำนวนที่ตรวจสอบ")),
                (
                    "quantity_defective",
                    models.IntegerField(default=0, verbose_name="จำนวนที่มีข้อบกพร่อง"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ตรวจสอบ",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="warehouse.goodsreceipt",
                        verbose_name="ใบเสร็จการรับ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "การตรวจสอบคุณภาพ",
                "verbose_name_plural": "การตรวจสอบคุณภาพ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "po_number",
                    models.CharField(max_length=100, unique=True, verbose_name="เลขที่ PO"),
                ),
                ("supplier_name", models.CharField(max_length=200, verbose_name="ชื่อผู้จัดส่ง")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการยืนยัน"),
                            ("confirmed", "ยืนยันแล้ว"),
                            ("shipped", "ส่งออกแล้ว"),
                            ("received", "รับแล้ว"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("expected_date", models.DateField(verbose_name="วันที่คาดว่าจะมาถึง")),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.warehouse",
                        verbose_name="คลังสินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบสั่งซื้อ",
                "verbose_name_plural": "ใบสั่งซื้อ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "picking_number",
                    models.CharField(max_length=100, unique=True, verbose_name="เลขที่เก็บสินค้า"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการเก็บ"),
                            ("in_progress", "กำลังเก็บ"),
                            ("completed", "เสร็จแล้ว"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "picked_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่เก็บ"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
                (
                    "picked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้เก็บ",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouse",
                        verbose_name="คลัง",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการเก็บสินค้า",
                "verbose_name_plural": "รายการเก็บสินค้า",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("quantity_required", models.IntegerField(verbose_name="จำนวนที่ต้องเก็บ")),
                ("quantity_picked", models.IntegerField(default=0, verbose_name="จำนวนที่เก็บได้")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.stocklocation",
                        verbose_name="ตำแหน่ง",
                    ),
                ),
                (
                    "picking_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.pickinglist",
                        verbose_name="รายการเก็บ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการเก็บสินค้า",
                "verbose_name_plural": "รายการเก็บสินค้า",
            },
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "parcel_number",
                    models.CharField(max_length=100, unique=True, verbose_name="เลขที่หีบห่อ"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="น้ำหนัก (kg)"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=100, verbose_name="ขนาด (L x W x H)"),
                ),
                (
                    "packed_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่บรรจุ"),
                ),
                (
                    "packed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บรรจุ",
                    ),
                ),
                (
                    "picking_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.pickinglist",
                        verbose_name="รายการเก็บ",
                    ),
                ),
            ],
            options={
                "verbose_name": "หีบห่อ",
                "verbose_name_plural": "หีบห่อ",
                "ordering": ["-packed_date"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("quantity_ordered", models.IntegerField(verbose_name="จำนวนที่สั่ง")),
                ("quantity_received", models.IntegerField(verbose_name="จำนวนที่รับ")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาต่อหน่วย"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.goodsreceipt",
                        verbose_name="ใบเสร็จ",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการเสร็จการรับสินค้า",
                "verbose_name_plural": "รายการเสร็จการรับสินค้า",
            },
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.purchaseorder",
                verbose_name="ใบสั่งซื้อ",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้รับ",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="warehouse.warehouse",
                verbose_name="คลัง",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("product", "warehouse")},
        ),
    ]
