# Generated by Django 4.2.14 on 2026-06-16 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "return_number",
                    models.CharField(max_length=100, unique=True, verbose_name="เลขที่การคืน"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_satisfied", "ไม่พอใจ"),
                            ("defective", "สินค้าเสียหาย"),
                            ("wrong_item", "ผิดรายการ"),
                            ("damaged_in_shipping", "เสียหายระหว่างขนส่ง"),
                            ("missing_parts", "ขาดชิ้นส่วน"),
                            ("other", "อื่นๆ"),
                        ],
                        max_length=50,
                        verbose_name="สาเหตุ",
                    ),
                ),
                ("description", models.TextField(verbose_name="คำอธิบายรายละเอียด")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการยืนยัน"),
                            ("approved", "อนุมัติแล้ว"),
                            ("shipped", "ส่งคืนแล้ว"),
                            ("received", "รับแล้ว"),
                            ("refunded", "คืนเงินแล้ว"),
                            ("rejected", "ปฏิเสธ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="จำนวนเงินคืน",
                    ),
                ),
                ("approval_notes", models.TextField(blank=True, verbose_name="หมายเหตุการอนุมัติ")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="ecommerce.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ขอโดย",
                    ),
                ),
            ],
            options={
                "verbose_name": "การคืนสินค้า",
                "verbose_name_plural": "การคืนสินค้า",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "shipment_number",
                    models.CharField(max_length=100, unique=True, verbose_name="เลขที่จัดส่ง"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="หมายเลขติดตาม"
                    ),
                ),
                ("origin_address", models.TextField(verbose_name="ที่อยู่ต้นทาง")),
                ("destination_address", models.TextField(verbose_name="ที่อยู่ปลายทาง")),
                ("recipient_name", models.CharField(max_length=200, verbose_name="ชื่อผู้รับ")),
                (
                    "recipient_phone",
                    models.CharField(max_length=20, verbose_name="เบอร์โทรศัพท์ผู้รับ"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="น้ำหนัก (kg)"
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=100, verbose_name="ขนาด")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการจัดส่ง"),
                            ("picked_up", "เก็บสินค้าแล้ว"),
                            ("in_transit", "กำลังขนส่ง"),
                            ("out_for_delivery", "ออกส่งแล้ว"),
                            ("delivered", "ส่งมอบแล้ว"),
                            ("failed", "ล้มเหลว"),
                            ("returned", "คืนแล้ว"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "picked_up_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่เก็บสินค้า"),
                ),
                (
                    "shipped_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่ส่ง"),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่ส่งมอบ"),
                ),
                (
                    "estimated_delivery",
                    models.DateField(blank=True, null=True, verbose_name="วันที่คาดว่าจะมาถึง"),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="ค่าจัดส่ง"),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="ค่าประกัน"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment",
                        to="ecommerce.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบจัดส่ง",
                "verbose_name_plural": "ใบจัดส่ง",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="ชื่อบริษัทจัดส่ง"),
                ),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="รหัส")),
                ("website", models.URLField(blank=True, verbose_name="เว็บไซต์")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="เบอร์โทรศัพท์"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="อีเมล")),
                ("api_endpoint", models.URLField(blank=True, verbose_name="API Endpoint")),
                ("api_key", models.CharField(blank=True, max_length=500, verbose_name="API Key")),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="อัตราพื้นฐาน"
                    ),
                ),
                (
                    "rate_per_kg",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="อัตราต่อ kg"
                    ),
                ),
            ],
            options={
                "verbose_name": "บริษัทจัดส่ง",
                "verbose_name_plural": "บริษัทจัดส่ง",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("report_date", models.DateField(unique=True, verbose_name="วันที่รายงาน")),
                ("total_shipments", models.IntegerField(default=0, verbose_name="รวมใบจัดส่ง")),
                ("delivered_count", models.IntegerField(default=0, verbose_name="จำนวนที่ส่งมอบ")),
                ("failed_count", models.IntegerField(default=0, verbose_name="จำนวนที่ล้มเหลว")),
                (
                    "in_transit_count",
                    models.IntegerField(default=0, verbose_name="จำนวนที่กำลังขนส่ง"),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="น้ำหนักรวม (kg)"
                    ),
                ),
                (
                    "total_shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="ค่าจัดส่งรวม"
                    ),
                ),
                (
                    "total_insurance_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="ค่าประกันรวม"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
            ],
            options={
                "verbose_name": "รายงานการจัดส่ง",
                "verbose_name_plural": "รายงานการจัดส่ง",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("picked_up", "เก็บสินค้า"),
                            ("in_transit", "กำลังขนส่ง"),
                            ("at_facility", "อยู่ที่สถานีกลาง"),
                            ("out_for_delivery", "ออกส่ง"),
                            ("delivery_attempted", "พยายามส่ง"),
                            ("delivered", "ส่งมอบแล้ว"),
                            ("returned", "คืนแล้ว"),
                        ],
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, verbose_name="ตำแหน่ง")),
                ("description", models.TextField(verbose_name="คำอธิบาย")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="เวลา")),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_history",
                        to="logistics.shipment",
                        verbose_name="ใบจัดส่ง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติติดตาม",
                "verbose_name_plural": "ประวัติติดตาม",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logistics.shippingprovider",
                verbose_name="บริษัทจัดส่ง",
            ),
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="จำนวน",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("unused", "ยังไม่ใช้"),
                            ("like_new", "เหมือนใหม่"),
                            ("good", "ดี"),
                            ("fair", "พอใช้"),
                        ],
                        default="fair",
                        max_length=50,
                        verbose_name="สภาพ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="logistics.return",
                        verbose_name="การคืน",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการคืนสินค้า",
                "verbose_name_plural": "รายการคืนสินค้า",
            },
        ),
        migrations.AddField(
            model_name="return",
            name="return_shipment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_request",
                to="logistics.shipment",
                verbose_name="ใบจัดส่งคืน",
            ),
        ),
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("date", models.DateField(verbose_name="วันที่")),
                ("start_time", models.TimeField(verbose_name="เวลาเริ่ม")),
                ("end_time", models.TimeField(verbose_name="เวลาสิ้นสุด")),
                (
                    "max_deliveries",
                    models.IntegerField(default=10, verbose_name="จำนวนการส่งสูงสุด"),
                ),
                (
                    "current_deliveries",
                    models.IntegerField(default=0, verbose_name="จำนวนการส่งปัจจุบัน"),
                ),
            ],
            options={
                "verbose_name": "ช่วงเวลาจัดส่ง",
                "verbose_name_plural": "ช่วงเวลาจัดส่ง",
                "ordering": ["date", "start_time"],
                "unique_together": {("date", "start_time", "end_time")},
            },
        ),
    ]
