# Generated by Django 4.2.14 on 2026-06-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="รหัสคูปอง")),
                ("description", models.TextField(blank=True, verbose_name="คำอธิบาย")),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("fixed", "ราคาคงที่"), ("percent", "เปอร์เซ็นต์")],
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="มูลค่าส่วนลด"
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ส่วนลดสูงสุด",
                    ),
                ),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="การซื้อขั้นต่ำ"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="วันเริ่มต้น")),
                ("end_date", models.DateTimeField(verbose_name="วันสิ้นสุด")),
                (
                    "usage_limit",
                    models.IntegerField(blank=True, null=True, verbose_name="ขีดจำกัดการใช้งาน"),
                ),
                ("usage_count", models.IntegerField(default=0, verbose_name="นับการใช้งาน")),
                (
                    "limited_to_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="จำกัดเฉพาะผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "คูปอง",
                "verbose_name_plural": "คูปอง",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อแคมเปญ")),
                ("subject", models.CharField(max_length=255, verbose_name="หัวข้อ")),
                ("body", models.TextField(verbose_name="เนื้อหา")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง"),
                            ("scheduled", "กำหนดเวลา"),
                            ("sending", "กำลังส่ง"),
                            ("sent", "ส่งแล้ว"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "send_to_new_users",
                    models.BooleanField(default=False, verbose_name="ส่งไปยังผู้ใช้ใหม่"),
                ),
                ("send_to_vip", models.BooleanField(default=False, verbose_name="ส่งไปยัง VIP")),
                (
                    "send_to_inactive",
                    models.BooleanField(default=False, verbose_name="ส่งไปยังผู้ใช้ที่ไม่ใช้งาน"),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่กำหนด"),
                ),
                (
                    "sent_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่ส่ง"),
                ),
                ("open_count", models.IntegerField(default=0, verbose_name="จำนวนการเปิด")),
                ("click_count", models.IntegerField(default=0, verbose_name="จำนวนการคลิก")),
                ("sent_count", models.IntegerField(default=0, verbose_name="จำนวนที่ส่ง")),
            ],
            options={
                "verbose_name": "แคมเปญส่งอีเมล",
                "verbose_name_plural": "แคมเปญส่งอีเมล",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("total_points", models.IntegerField(default=0, verbose_name="รวมแต้ม")),
                (
                    "lifetime_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="มูลค่าตลอดชีวิต"
                    ),
                ),
            ],
            options={
                "verbose_name": "แต้มความจงรักษ์",
                "verbose_name_plural": "แต้มความจงรักษ์",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="ชื่อโปรแกรม")),
                ("description", models.TextField(verbose_name="คำอธิบาย")),
                (
                    "points_per_purchase",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=8, verbose_name="แต้มต่อการซื้อ"
                    ),
                ),
                (
                    "points_expiry_days",
                    models.IntegerField(default=365, verbose_name="วันหมดอายุแต้ม"),
                ),
            ],
            options={
                "verbose_name": "โปรแกรมจำนนลูกค้า",
                "verbose_name_plural": "โปรแกรมจำนนลูกค้า",
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "ได้รับ"),
                            ("redeem", "แลก"),
                            ("expire", "หมดอายุ"),
                            ("adjust", "ปรับปรุง"),
                        ],
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                ("points_amount", models.IntegerField(verbose_name="จำนวนแต้ม")),
                ("reference", models.CharField(blank=True, max_length=200, verbose_name="อ้างอิง")),
                ("description", models.TextField(blank=True, verbose_name="คำอธิบาย")),
                (
                    "loyalty_points",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="marketing.loyaltypoints",
                        verbose_name="แต้ม",
                    ),
                ),
            ],
            options={
                "verbose_name": "ธุรกรรมแต้ม",
                "verbose_name_plural": "ธุรกรรมแต้ม",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อระดับ")),
                ("min_points", models.IntegerField(default=0, verbose_name="คะแนนขั้นต่ำ")),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="ส่วนลด (%)"
                    ),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="สิทธิพิเศษ")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="marketing.loyaltyprogram",
                        verbose_name="โปรแกรม",
                    ),
                ),
            ],
            options={
                "verbose_name": "ระดับสมาชิก",
                "verbose_name_plural": "ระดับสมาชิก",
                "ordering": ["min_points"],
            },
        ),
        migrations.AddField(
            model_name="loyaltypoints",
            name="current_tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketing.membershiptier",
                verbose_name="ระดับปัจจุบัน",
            ),
        ),
        migrations.AddField(
            model_name="loyaltypoints",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="marketing.loyaltyprogram",
                verbose_name="โปรแกรม",
            ),
        ),
        migrations.AddField(
            model_name="loyaltypoints",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_points",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ใช้",
            ),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("recipient", models.EmailField(max_length=254, verbose_name="ผู้รับ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการส่ง"),
                            ("sent", "ส่งแล้ว"),
                            ("failed", "ล้มเหลว"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("opened", models.BooleanField(default=False, verbose_name="เปิดแล้ว")),
                (
                    "opened_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่เปิด"),
                ),
                ("clicked", models.BooleanField(default=False, verbose_name="คลิกแล้ว")),
                (
                    "clicked_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่คลิก"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="marketing.emailcampaign",
                        verbose_name="แคมเปญ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "บันทึกอีเมล",
                "verbose_name_plural": "บันทึกอีเมล",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนส่วนลด"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="marketing.coupon",
                        verbose_name="คูปอง",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecommerce.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "การใช้งานคูปอง",
                "verbose_name_plural": "การใช้งานคูปอง",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อแคมเปญ")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(verbose_name="คำอธิบาย")),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("discount", "ส่วนลด"),
                            ("bundle", "สินค้าจำหน่ายเพิ่มเติม"),
                            ("seasonal", "ตามฤดูกาล"),
                            ("flash_sale", "ลดราคาเบิกน้อย"),
                            ("new_customer", "ลูกค้าใหม่"),
                        ],
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="วันเริ่มต้น")),
                ("end_date", models.DateTimeField(verbose_name="วันสิ้นสุด")),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="ส่วนลด (%)"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="ส่วนลด (ราคา)"
                    ),
                ),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="การซื้อขั้นต่ำ"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="งบประมาณ"),
                ),
                (
                    "used_budget",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="งบประมาณที่ใช้"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaigns/", verbose_name="รูปภาพ"
                    ),
                ),
                (
                    "target_products",
                    models.ManyToManyField(
                        related_name="campaigns",
                        to="ecommerce.product",
                        verbose_name="สินค้าเป้าหมาย",
                    ),
                ),
            ],
            options={
                "verbose_name": "แคมเปญ",
                "verbose_name_plural": "แคมเปญ",
                "ordering": ["-start_date"],
            },
        ),
    ]
