# Generated by Django 4.2.14 on 2026-06-16 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("quantity", models.IntegerField(default=0, verbose_name="จำนวนรายการ")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="ราคารวม"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตะกร้าสินค้า",
                "verbose_name_plural": "ตะกร้าสินค้า",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="ชื่อหมวดหมู่"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="คำอธิบาย")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="categories/", verbose_name="รูปภาพ"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ecommerce.category",
                        verbose_name="หมวดหมู่หลัก",
                    ),
                ),
            ],
            options={
                "verbose_name": "หมวดหมู่สินค้า",
                "verbose_name_plural": "หมวดหมู่สินค้า",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="เลขที่คำสั่ง"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการยืนยัน"),
                            ("confirmed", "ยืนยันแล้ว"),
                            ("preparing", "กำลังเตรียมสินค้า"),
                            ("shipped", "ส่งออกแล้ว"),
                            ("delivered", "จัดส่งแล้ว"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="ที่อยู่จัดส่ง")),
                ("shipping_phone", models.CharField(max_length=20, verbose_name="เบอร์โทรศัพท์")),
                ("shipping_name", models.CharField(max_length=200, verbose_name="ชื่อผู้รับ")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ยอดรวมสินค้า"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="ค่าจัดส่ง"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="ส่วนลด"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ยอดรวมทั้งสิ้น"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, verbose_name="หมายเลขติดตาม"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำสั่งซื้อ",
                "verbose_name_plural": "คำสั่งซื้อ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("sku", models.CharField(max_length=100, unique=True, verbose_name="รหัสสินค้า")),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อสินค้า")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(verbose_name="คำอธิบาย")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="ราคา"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="ต้นทุน"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="ส่วนลด (%)"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="รูปภาพหลัก")),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="สต็อก",
                    ),
                ),
                ("min_stock", models.IntegerField(default=5, verbose_name="สต็อกขั้นต่ำ")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="คะแนน",
                    ),
                ),
                ("review_count", models.IntegerField(default=0, verbose_name="จำนวนรีวิว")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="ecommerce.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
            ],
            options={
                "verbose_name": "สินค้า",
                "verbose_name_plural": "สินค้า",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("image", models.ImageField(upload_to="products/", verbose_name="รูปภาพ")),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=255, verbose_name="ข้อความทดแทน"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปภาพสินค้า",
                "verbose_name_plural": "รูปภาพสินค้า",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "โอนเงินผ่านธนาคาร"),
                            ("credit_card", "บัตรเครดิต/เดบิต"),
                            ("ebanking", "ธนาคารอิเล็กทรอนิกส์"),
                            ("wallet", "กระเป๋าดิจิทัล"),
                            ("cod", "ชำระเงินเมื่อรับสินค้า"),
                        ],
                        max_length=20,
                        verbose_name="วิธีการชำระ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการชำระ"),
                            ("completed", "ชำระแล้ว"),
                            ("failed", "ล้มเหลว"),
                            ("refunded", "คืนเงินแล้ว"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="จำนวนเงิน"),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=200, verbose_name="เลขที่อ้างอิง"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="ecommerce.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
            ],
            options={
                "verbose_name": "การชำระเงิน",
                "verbose_name_plural": "การชำระเงิน",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("product_name", models.CharField(max_length=255, verbose_name="ชื่อสินค้า")),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="จำนวน",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="ราคา"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecommerce.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการคำสั่งซื้อ",
                "verbose_name_plural": "รายการคำสั่งซื้อ",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="จำนวน",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="ราคา"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecommerce.cart",
                        verbose_name="ตะกร้า",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการในตะกร้า",
                "verbose_name_plural": "รายการในตะกร้า",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="คะแนน",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อ")),
                ("comment", models.TextField(verbose_name="ความเห็น")),
                ("is_approved", models.BooleanField(default=False, verbose_name="อนุมัติแล้ว")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="ecommerce.product",
                        verbose_name="สินค้า",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "รีวิว",
                "verbose_name_plural": "รีวิว",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="ecommerce_p_sku_35a263_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="ecommerce_p_categor_61fd86_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active"], name="ecommerce_p_is_acti_46ccda_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_number"], name="ecommerce_o_order_n_bae905_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="ecommerce_o_user_id_20253d_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="ecommerce_o_status_27d41d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
