# Generated by Django 4.2.14 on 2026-06-23 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="เวลาสร้าง")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="เวลาแก้ไข")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="รหัสสินค้า (SKU)"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="สี/เฉดสี"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ขนาด/ไซส์"
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ราคาพิเศษ",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="สต็อก",
                    ),
                ),
                ("min_stock", models.IntegerField(default=5, verbose_name="สต็อกขั้นต่ำ")),
            ],
            options={
                "verbose_name": "ตัวเลือกสินค้า (SKU)",
                "verbose_name_plural": "ตัวเลือกสินค้า (SKU)",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "คำสั่งซื้อ / ใบเสร็จ",
                "verbose_name_plural": "คำสั่งซื้อ / ใบเสร็จ",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "สินค้าหลัก",
                "verbose_name_plural": "สินค้าหลัก",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="ecommerce_o_user_id_20253d_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="ecommerce_p_sku_35a263_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="ecommerce_p_is_acti_46ccda_idx",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="base_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ต้นทุนเริ่มต้น"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="ราคาเริ่มต้น"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50, unique=True, verbose_name="เลขที่คำสั่ง/ใบเสร็จ"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True, verbose_name="ที่อยู่จัดส่ง"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ชื่อผู้รับ"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการยืนยัน"),
                    ("confirmed", "ยืนยันแล้ว"),
                    ("preparing", "กำลังเตรียมสินค้า"),
                    ("shipped", "ส่งออกแล้ว"),
                    ("delivered", "จัดส่งแล้ว"),
                    ("cancelled", "ยกเลิก"),
                    ("pos_completed", "ขายหน้าร้านสำเร็จ"),
                ],
                default="pending",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ลูกค้า",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="ชื่อสินค้า (บันทึกประวัติ)"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "โอนเงินผ่านธนาคาร"),
                    ("credit_card", "บัตรเครดิต/เดบิต"),
                    ("ebanking", "ธนาคารอิเล็กทรอนิกส์"),
                    ("wallet", "กระเป๋าดิจิทัล"),
                    ("cod", "ชำระเงินเมื่อรับสินค้า"),
                    ("cash", "เงินสด (หน้าร้าน)"),
                ],
                max_length=20,
                verbose_name="วิธีการชำระ",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="ecommerce.product",
                verbose_name="สินค้าหลัก",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce.productvariant",
                verbose_name="ตัวเลือกสินค้า",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.productvariant",
                verbose_name="ตัวเลือกสินค้า",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "variant")},
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "color", "size")},
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
    ]
